### PR TITLE
Milestone 1- Styling Header and Footer

### PR DESCRIPTION
**Pull request by MaiRizk**
This PR includes; 

1- Structure the header and footer. 
2- Using bootstrap to style the page.
3- Make the design responsive for mobile, tablet, and desktop.

### CODE REVIEW

**Review by mricanho — CHANGES_REQUESTED** [review]
# 🔴  Changes Required 🔴  

Hello @MaiRizk @ad9311, you did an impressive job in your first milestone, the clone looks nearly identical to the original, congrats🔥, just a few changes are required:

- [x] **_Your README file it's empty, and it's always super important, you need to fill it properly so your project will look professional_**
- [x]  **Use semantic HTML, the nav tag for your navbar is missing**
- [x] **You missed the form with the search field in the second nav, please add it**
- [x] **In the mobile version(320px), the width of your first nav(red background), it's not reaching the width of the screen, kindly fix it**

That's it, few details, good job!
nice

**As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561#) you have 2 code reviews left for this project.**

You can contact me on slack if you have any questions just search for me as @ Miguel Ricaño.

### 💻 👩🏽‍💻  Happy Coding!👨🏽‍💻  🖥️

**Comment by ad9311** [comment]
# Greetings! 👋🏽

@MaiRizk  and I @ad9311  have finish making the necessary changes to fix the above mentioned issues.

These include:
- Updated the README file
- Used nav tag for the navbar
- Added the search field and search icon on the right side of the navbar
- In the mobile version (320px) and below the navbar does no longer shrinks
- Also added hover effects and font styling to make it resemble more to the original

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
💪✔**Hey guys, You have really done a good job implementing the changes requested by the previous reviewer, and your project looks good.** Let's just fix few things before we move.
### Required changes👈
1. The readme file is missing information on how to have a copy of the project, explain like you are telling someone who is not a programmer.
2. You have used the nav tag almost everywhere, the nav tag is used for the nav menu, can not be found in the footer. Please read about HTML semantic tags.
_When you finish, submit another review request_
**Remember** You are only remaining with one review request, according to the review policy.

**[OPTIONAL]**
1. The search icon and input should be a link.
2. The hamburger should be a link too.
In case you have a question about the review, you can reach me on slack as Elisha kyakopo.

**Comment by ad9311** [comment]
# Greetings! 👋🏽

@MaiRizk and I @ad9311 have finish making the necessary changes to fix the above mentioned issues.

These include:
- **Required**

1. Updated the README file. Now it has information on how to clone the project.
2. Remove unnecessary navs. Only the top links are enclosed in a nav.

- Optional

1. The hamburger icon is a link.

**Review by DeliceLydia — APPROVED** [review]
# Status: Approved image

Congratulations #MaiRizk and @ad9311 for implementing all changes requested by the previous TSE's

## Optional 

I can't see the nav elements on the desktop view I don't know what happened,  try to check everything before moving on to the next milestone as it can cause you trouble in the future clarify everything before moving on 

your page

ele

original

ogn

- Check what to change by comparing the original

## Feel free to merge when you see that there will be no harm in the future

All the best,

Lydia Ingabire

**Pull request merged**
