### PR TITLE
Milestone 3- Styling Last Sections #3

### PR DESCRIPTION
**Pull request by ad9311**
This PR includes;
1. Structure the 3 columns using semantic HTML.
2. Design the last remaining sections using bootstrap.
3. Make the design responsive for 3 screens.

### CODE REVIEW

**Review by george-shammar — CHANGES_REQUESTED** [review]
STATUS: CHANGES REQUESTED :recycle: :recycle: 

**Your progress through the various milestones have been really impressive. Please keep it going.** :+1: 

**However, you need to make the following changes in order to make the project approvable. Please note that since this is the last milestone, required changes may include some aspects of the previous two milestones:**

- [ ] Your project is incomplete. Vital sections of this milestone is missing. You only implemented the "Editor's pick" section. Other sections missing include the following:
- In the magazine
- Main newspaper (US, World, Business, Tech & science, culture, sports e.t.c)
- Subscribe
- Newsletter
Please implement these sections.

**From the previous milestone**

- [ ] In the tablet version, please make the changes below:
Original
original

Yours
newstab



Please make the neccessary changes and submit another CRR when you're ready.

:red_circle: **As described in the** [Code reviews limit Policy ](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), **you have 2 code reviews left for this project.**

**Happy coding** :laughing:

**Comment by ad9311** [comment]
## Greetings! 👋🏽

We have doublechecked and as of today the **Milestone-3** have all the sections just like the original. **There are not any missing.**

We implemented the following fix according to this code review:
This include:
- Fix the width of the **Sponsored Insight** section (jus below the the Opinion Section) in the tablet view to make it like the original one.

**Comment by george-shammar** [comment]
> ## Greetings! 👋🏽
> 
> We have doublechecked and as of today the **Milestone-3** have all the sections just like the original. **There are not any missing.**
> 
> We implemented the following fix according to this code review:
> This include:
> 
>     * Fix the width of the **Sponsored Insight** section (jus below the the Opinion Section) in the tablet view to make it like the original one.

Hello @ad9311 and @MaiRizk, I dropped a message for both of you on slack. Would you be available to jump on a zoom call with me now?

**Review by george-shammar — APPROVED** [review]
### **STATUS : APPROVED** :heavy_check_mark: :heavy_check_mark: :+1: 

**Good job! You've done an awesome job and thank you for implementing the required changes.** :ok_hand: 

[OPTIONAL]

- [ ] Please ensure that the live demo of your project is updated.

**You may now go ahead and merge this branch.**

**Congratulations.** :wine_glass: :wine_glass: 

**I wish you good luck with your future projects.**

**Pull request merged**
